export const appDescription = "Kiwi2333 的个人博客 | Kiwi2333's Blog ，一个分享日常的博客，这个平台上可以找到很多有趣的博客内容 🎉"
export const appName = "Kiwi2333's Blog 🎉"
export const appPWAName = "Kiwi2333's Blog 🎉"
export const selfName = "Kiwi2333"
export const appLang = "zh-CN"
export const icpCode = "粤ICP备2025414133号-1"
export const icpLink = "https://beian.miit.gov.cn/"
